// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Persistence;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250408062622_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a623450-2827-4068-8a8a-3dc0c14b0dfd"),
                            BirthPlace = "New York",
                            DateOfBirth = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            Gender = 0,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("3b273f6a-4710-4059-bd97-c5891fc5ab5b"),
                            BirthPlace = "Los Angeles",
                            DateOfBirth = new DateTime(1985, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            Gender = 1,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("3711ada9-cd02-47da-8d48-c0a864218d40"),
                            BirthPlace = "Chicago",
                            DateOfBirth = new DateTime(1992, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alex",
                            Gender = 2,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("4d7fc689-e9e2-4560-abb0-c1e0bc84fb20"),
                            BirthPlace = "Houston",
                            DateOfBirth = new DateTime(1988, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emily",
                            Gender = 1,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = new Guid("faf5dabb-ad59-4167-ae41-f6170e93cf9f"),
                            BirthPlace = "Phoenix",
                            DateOfBirth = new DateTime(1995, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Chris",
                            Gender = 0,
                            LastName = "Anderson"
                        },
                        new
                        {
                            Id = new Guid("ab852f0f-402a-4ac1-a224-1d856d85ad9f"),
                            BirthPlace = "Seattle",
                            DateOfBirth = new DateTime(1983, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anna",
                            Gender = 1,
                            LastName = "Thomas"
                        },
                        new
                        {
                            Id = new Guid("83c00f3a-b23b-4bfa-8122-b2890c0125c5"),
                            BirthPlace = "Boston",
                            DateOfBirth = new DateTime(1979, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            Gender = 0,
                            LastName = "Jackson"
                        },
                        new
                        {
                            Id = new Guid("b53ba950-3443-495e-9582-cecf00814035"),
                            BirthPlace = "Denver",
                            DateOfBirth = new DateTime(1993, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Laura",
                            Gender = 1,
                            LastName = "White"
                        },
                        new
                        {
                            Id = new Guid("1bb593dc-7119-475a-9cb9-51deba8ef12c"),
                            BirthPlace = "Miami",
                            DateOfBirth = new DateTime(1987, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            Gender = 0,
                            LastName = "Harris"
                        },
                        new
                        {
                            Id = new Guid("3be9998c-d61e-49dd-8a9b-79f3339e41df"),
                            BirthPlace = "San Francisco",
                            DateOfBirth = new DateTime(1991, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sophia",
                            Gender = 1,
                            LastName = "Martin"
                        },
                        new
                        {
                            Id = new Guid("ced53c45-36c0-429e-98c5-32931c262bba"),
                            BirthPlace = "New York",
                            DateOfBirth = new DateTime(1980, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "James",
                            Gender = 0,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("44451e65-302c-4292-94b9-50f523f4858c"),
                            BirthPlace = "Los Angeles",
                            DateOfBirth = new DateTime(1996, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Olivia",
                            Gender = 1,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("5df21aa4-5369-4572-b8f7-6efab0fce33b"),
                            BirthPlace = "Chicago",
                            DateOfBirth = new DateTime(1984, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daniel",
                            Gender = 0,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("c8292d8e-86f1-4182-b6b4-fa39d513aa32"),
                            BirthPlace = "Houston",
                            DateOfBirth = new DateTime(1986, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Grace",
                            Gender = 1,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = new Guid("12aa065d-a0d8-4591-999e-e8c1ba1fb900"),
                            BirthPlace = "Phoenix",
                            DateOfBirth = new DateTime(1990, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Matthew",
                            Gender = 0,
                            LastName = "Anderson"
                        },
                        new
                        {
                            Id = new Guid("ba511023-2db1-48a3-9b06-cd95cf0cc0b1"),
                            BirthPlace = "Seattle",
                            DateOfBirth = new DateTime(1994, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zoe",
                            Gender = 1,
                            LastName = "Thomas"
                        },
                        new
                        {
                            Id = new Guid("1f859c82-7d62-4d9a-8cd6-81e470c9a14b"),
                            BirthPlace = "Boston",
                            DateOfBirth = new DateTime(1997, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ryan",
                            Gender = 0,
                            LastName = "Jackson"
                        },
                        new
                        {
                            Id = new Guid("2a8c80b4-6b68-4574-8647-b4debe7699f6"),
                            BirthPlace = "Denver",
                            DateOfBirth = new DateTime(1982, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lily",
                            Gender = 1,
                            LastName = "White"
                        },
                        new
                        {
                            Id = new Guid("e8f55c70-ad1d-4191-a3d8-0d044150fca1"),
                            BirthPlace = "Miami",
                            DateOfBirth = new DateTime(1981, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Andrew",
                            Gender = 0,
                            LastName = "Harris"
                        },
                        new
                        {
                            Id = new Guid("d3f44ab1-eb31-41f6-867f-7ec9f659207a"),
                            BirthPlace = "San Francisco",
                            DateOfBirth = new DateTime(1998, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Chloe",
                            Gender = 1,
                            LastName = "Martin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
