// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Persistence;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_CS_AS");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_CS_AS");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BirthPlace = "New York",
                            DateOfBirth = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            Gender = 0,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BirthPlace = "Los Angeles",
                            DateOfBirth = new DateTime(1985, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            Gender = 1,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BirthPlace = "Chicago",
                            DateOfBirth = new DateTime(1992, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alex",
                            Gender = 2,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BirthPlace = "Houston",
                            DateOfBirth = new DateTime(1988, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emily",
                            Gender = 1,
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BirthPlace = "Phoenix",
                            DateOfBirth = new DateTime(1995, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Chris",
                            Gender = 0,
                            LastName = "Anderson"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            BirthPlace = "Seattle",
                            DateOfBirth = new DateTime(1983, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anna",
                            Gender = 1,
                            LastName = "Thomas"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            BirthPlace = "Boston",
                            DateOfBirth = new DateTime(1979, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            Gender = 0,
                            LastName = "Jackson"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            BirthPlace = "Denver",
                            DateOfBirth = new DateTime(1993, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Laura",
                            Gender = 1,
                            LastName = "White"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            BirthPlace = "Miami",
                            DateOfBirth = new DateTime(1987, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            Gender = 0,
                            LastName = "Harris"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BirthPlace = "San Francisco",
                            DateOfBirth = new DateTime(1991, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sophia",
                            Gender = 1,
                            LastName = "Martin"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BirthPlace = "Atlanta",
                            DateOfBirth = new DateTime(1989, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Matthew",
                            Gender = 0,
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BirthPlace = "Dallas",
                            DateOfBirth = new DateTime(1996, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Chloe",
                            Gender = 1,
                            LastName = "Nguyen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
